### ISSUE TITLE
Error during compiler-macroexpansion of

### ISSUE THREAD

**Issue by muyinliu** [alex-gutev/static-dispatch#1]
I wrote a small demo:

```lisp
(ql:quickload 'static-dispatch)

(declaim (inline sum))
(defgeneric sum (a b)
  (:documentation "sum two values"))

(static-dispatch:defmethod sum ((a fixnum) (b fixnum))
  (declare (optimize (speed 3) (safety 0) (debug 0)))
  (+ a b))

(defun test-sum-inline (a b)
  (declare (optimize (speed 3) (safety 0) (debug 0))
           (type fixnum a b))
  (sum a b))
```

but SBCL v1.3.21 with errors occur when compile function `test-sum-inline`:

```=>
; in: DEFUN TEST-SUM-INLINE
;     (SUM A B)
; 
; caught WARNING:
;   Error during compiler-macroexpansion of (SUM A B). Use *BREAK-ON-SIGNALS* to
;   intercept.
;   
;    invalid number of arguments: 1
; 
; compilation unit finished
;   caught 1 WARNING condition
```

Did I use **static-dispatch** in the wrong way? Could you please give me a working demo?

**Comment by pfdietz** [comment]
Should you have used static-dispatch:defgeneric, instead of cl:defgeneric?

**Comment by alex-gutev** [comment]
Your use of static-dispatch is mostly correct, other than that the generic function is declared with `cl:defgeneric` rather than `static-dispatch:defgeneric`, however in this case it shouldn't make a difference, as you're not declaring any methods in the `defgeneric` form, and it is not the cause of the error. 

This is most likely a bug. I'm having trouble reproducing the issue at the moment on my own machine. Can you set `*BREAK-ON-SIGNALS*` to true and post the resulting error and stack trace (only the top few functions are necessary).

**Comment by muyinliu** [comment]
```
(setf *BREAK-ON-SIGNALS* t)

(defun test-sum-inline (a b)
  (declare (optimize (speed 3) (safety 0) (debug 0))
           (type fixnum a b))
  (sum a b))
```
=>
```=>
debugger invoked on a SIMPLE-CONDITION in thread
#<THREAD "main thread" RUNNING {1001976C43}>:
  invalid number of arguments: 1
BREAK was entered because of *BREAK-ON-SIGNALS* (now rebound to NIL).

Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [CONTINUE] Return from BREAK.
  1: [REASSIGN] Return from BREAK and assign a new value to *BREAK-ON-SIGNALS*.
  2: [ABORT   ] Exit debugger, returning to top level.

(STATIC-DISPATCH::ORDER-METHOD-SPECIALIZERS (0 1)) [external]
   source: (DEFUN ORDER-METHOD-SPECIALIZERS (METHODS PRECEDENCE)
             "Orders the specializers of METHODS by the argument precedence order
   PRECEDENCE."
             (FLET ((ORDER-SPECIALIZERS (METHOD)
                      (CONS (ORDER-BY-PRECEDENCE PRECEDENCE #) (CDR METHOD))))
               (MAPCAR #'ORDER-SPECIALIZERS METHODS)))
0]
```

And other info:

- SBCL v1.3.21

**Comment by alex-gutev** [comment]
Are you using the latest version of static-dispatch?

**Comment by muyinliu** [comment]
> Are you using the latest version of static-dispatch? The latest version is 0.3.

Yes, I'm using the latest version of static-dispatch.

And using `static-dispatch:defgeneric` to replace `cl-defgeneric` like this:

```
(ql:quickload 'static-dispatch)

(declaim (inline sum))
(static-dispatch:defgeneric sum (a b)
  (:documentation "sum two values"))

(static-dispatch:defmethod sum ((a fixnum) (b fixnum))
  (declare (optimize (speed 3) (safety 0) (debug 0)))
  (+ a b))

(defun test-sum-inline (a b)
  (declare (optimize (speed 3) (safety 0) (debug 0))
           (type fixnum a b))
  (sum a b))
```

SBCL v1.3.21 still throw the same WARNING:

```
; in: DEFUN TEST-SUM-INLINE
;     (SUM A B)
;
; caught WARNING:
;   Error during compiler-macroexpansion of (SUM A B). Use *BREAK-ON-SIGNALS* to
;   intercept.
;
;    invalid number of arguments: 1
;
; compilation unit finished
;   caught 1 WARNING condition

TEST-SUM-INLINE
```

**Comment by alex-gutev** [comment]
Make sure you're using the latest commit, on the master branch, of [cl-environments](https://github.com/alex-gutev/cl-environments). I fixed a few bugs in that projects a while ago.

**Comment by muyinliu** [comment]
> Make sure you're using the latest commit, on the master branch, of [cl-environments](https://github.com/alex-gutev/cl-environments). I fixed a few bugs in that project a while ago.

Yes. static-dispatch: `5224433b`, cl-environments:  `bbcd958a`

**Comment by alex-gutev** [comment]
The error you're getting is strange as it indicates that the first argument to the function `ORDER-METHOD-SPECIALIZERS` (which is a function of two arguments) is being omitted and only the second argument is being passed. I have been unable to reproduce the issue, even when running on SBCL 1.3.21. Both arguments are correctly being passed and no error is thrown by SBCL.

`ORDER-METHOD-SPECIALIZERS` is called within the `STATIC-OVERLOAD` function in the following form:

_Located on line 290 of `src/static-dispatch.lisp`_

```
(-<> (aand (gf-methods gf-name) (hash-table-alist it))
         (order-method-specializers precedence 1)
         (applicable-methods types)
         (sort-methods)
         (mapcar #'cdr <>))
```

The only cause for the issue that I can think of is that either your copy of static-dispatch has been modified somehow (which I doubt, however check that it matches the above) or there is an issue with your copy of `cl-arrows`, which provides the `-<>` macro, used above. I'm using the `cl-arrows` version, which was last updated on 2016-03-18, provided in the latest quicklisp distribution.

Try replacing the above (within `static-dispatch.lisp`):

```
(MAPCAR #'CDR
     (SORT-METHODS
     (APPLICABLE-METHODS
         (ORDER-METHOD-SPECIALIZERS
                (AAND (GF-METHODS GF-NAME) (HASH-TABLE-ALIST IT)) PRECEDENCE 1)
	       TYPES)))
```

In order to determine whether `cl-arrows` is the cause.

**Comment by digikar99** [comment]
Yeah, `cl-arrows` fetched from the latest quicklisp distribution worked for me; in my case, I did have a local copy of `cl-arrows` that caused the issue
